"""Parse the version header of every proto/algogators/*.proto into algogators/versions.py.

    python gen_versions.py <proto dir> <output versions.py>

Each .proto must start with the header block (docs/design/rpc.md):

    // AlgoGators gRPC API
    // API: <api>
    // Version: <major>.<minor>.<patch>
    // Compatibility: ...

where <api> is the file name without .proto and the file's package is algogators.<api>. The
generated API_VERSIONS is the only place the server and its clients read a version from, so the
header in the .proto is the single source. Any file that breaks the rules stops generation.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = "// AlgoGators gRPC API"
_API = re.compile(r"^// API: ([a-z][a-z0-9_]*)$")
_VERSION = re.compile(r"^// Version: (\d+\.\d+\.\d+)$")
_PACKAGE = re.compile(r"^package ([A-Za-z0-9_.]+);$", re.MULTILINE)


def parse(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if len(lines) < 4 or lines[0] != HEADER or not lines[3].startswith("// Compatibility:"):
        raise SystemExit(f"{path}: must start with the AlgoGators gRPC API header block")
    api, version = _API.match(lines[1]), _VERSION.match(lines[2])
    if not api or not version:
        raise SystemExit(f"{path}: header needs '// API: <name>' then '// Version: X.Y.Z'")
    if api.group(1) != path.stem:
        raise SystemExit(f"{path}: API '{api.group(1)}' must equal the file name '{path.stem}'")
    package = _PACKAGE.search(text)
    if not package or package.group(1) != f"algogators.{path.stem}":
        raise SystemExit(f"{path}: package must be algogators.{path.stem}")
    return api.group(1), version.group(1)


def render(versions: dict) -> str:
    body = "".join(f'    "{api}": "{versions[api]}",\n' for api in sorted(versions))
    return ('"""Generated by gen_versions.py from the version header of each '
            'proto/algogators/*.proto.\n\nDo not edit: change the "Version:" line of the .proto '
            'and regenerate.\n"""\n\nAPI_VERSIONS = {\n' + body + "}\n")


def main(argv: list[str]) -> int:
    proto_dir, out = Path(argv[1]), Path(argv[2])
    files = sorted(proto_dir.glob("*.proto"))
    if not files:
        raise SystemExit(f"no .proto files in {proto_dir}")
    versions = dict(parse(p) for p in files)
    out.write_text(render(versions), encoding="utf-8", newline="\n")
    print(f"wrote {out}: " + ", ".join(f"{a}={v}" for a, v in sorted(versions.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
