"""Fast, offline contracts for the QT certification harness.

These tests never start Docker, open a socket, import the AlgoLens application,
or execute the C++ probe.  They protect the test-only safety and evidence code
that must run *before* the disposable integration environment is created.
"""

import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys

import pytest


HARNESS = Path(__file__).parent / "integration" / "test_qt_report_pipeline.py"
SPEC = importlib.util.spec_from_file_location("qt_report_pipeline", HARNESS)
qt = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(qt)


def test_unsafe_transport_or_production_environment_is_rejected():
    """A future acceptance of SMTP/prod config must fail before side effects."""
    for key in ("SMTP_HOST", "SMTP_URL", "DATABASE_URL", "QT_PIPELINE_TEST_DSN"):
        with pytest.raises(qt.UnsafeCertificationInput, match=key):
            qt.validate_invocation_environment({key: "must-not-be-consumed"})

    qt.validate_invocation_environment({"PATH": "/synthetic/bin", "LANG": "C"})


def test_csv_and_html_positions_are_keyed_by_strategy_and_symbol():
    """Swapping quantities between strategies must not satisfy the assertion."""
    csv_text = """# Portfolio Value: 1, Date: 2026-09-21
strategy,symbol,quantity,market_price
Trend Following,ES.v.0,7,5000
Trend Following Fast,ES.v.0,-3,5000
"""
    html_text = """<h2>Today's Positions</h2>
<h3>Trend Following</h3><table><tr><th>Symbol</th><th>Quantity</th><th>Market Price</th><th>Notional</th><th>% of Total</th></tr>
<tr><td>ES.v.0</td><td>7</td><td>$5000.00</td><td>$35,000.00</td><td>100.00%</td></tr></table>
<h3>Trend Following Fast</h3><table><tr><th>Symbol</th><th>Quantity</th><th>Market Price</th><th>Notional</th><th>% of Total</th></tr>
<tr><td>ES.v.0</td><td>-3</td><td>$5000.00</td><td>$15,000.00</td><td>100.00%</td></tr></table><div class="metrics-section">rest</div>"""
    expected = {
        ("Trend Following", "ES.v.0"): 7.0,
        ("Trend Following Fast", "ES.v.0"): -3.0,
    }
    qt.assert_position_quantities(qt.parse_csv_positions(csv_text), expected, "CSV")
    qt.assert_position_quantities(qt.parse_html_positions(html_text), expected, "HTML")

    swapped = dict(expected)
    swapped[("Trend Following", "ES.v.0")] = -3.0
    swapped[("Trend Following Fast", "ES.v.0")] = 7.0
    with pytest.raises(AssertionError, match="CSV"):
        qt.assert_position_quantities(swapped, expected, "CSV")


def test_non_position_comparison_allows_position_changes_only():
    """An unrelated report-text mutation must fail the invariant."""
    before_csv = "# Date: 2026-09-21\nstrategy,symbol,quantity\nA,ES,12\n"
    after_csv = "# Date: 2026-09-21\nstrategy,symbol,quantity\nA,ES,7\n"
    before_html = (
        "<h1>Daily Trading Report</h1><h2>Today's Positions</h2>"
        "<h3>A</h3><table>"
        "<tr><th>Symbol</th><th>Quantity</th><th>Market Price</th>"
        "<th>Notional</th><th>% of Total</th></tr>"
        "<tr><td>ES.v.0</td><td>12</td><td>$5000.00</td>"
        "<td>$60,000.00</td><td>100.00%</td></tr></table>"
        "<div><strong>Positions:</strong> 1 | <strong>Notional:</strong> $60,000.00 | "
        "<strong>Margin:</strong> $12,000.00</div>"
        '<div class="summary-stats"><div class="metric">'
        "<strong>Active Positions:</strong> 1</div></div>"
        '<div class="metrics-section"><h2>Portfolio Snapshot</h2></div>'
        "<footer>Generated by AlgoGators</footer>"
    )
    after_html = (
        before_html.replace("<td>12</td>", "<td>7</td>")
        .replace("$60,000.00", "$35,000.00")
        .replace("$12,000.00", "$7,000.00")
    )
    qt.assert_non_position_unchanged(before_csv, before_html, after_csv, after_html)

    with pytest.raises(AssertionError, match="static HTML"):
        qt.assert_non_position_unchanged(
            before_csv,
            before_html,
            after_csv,
            after_html.replace("AlgoGators", "unrelated mutation"),
        )

    with pytest.raises(AssertionError, match="static HTML"):
        qt.assert_non_position_unchanged(
            before_csv,
            before_html,
            after_csv,
            after_html.replace("<h3>A</h3>", "<h3>A</h3><p>unexpected insertion</p>"),
        )

    with pytest.raises(AssertionError, match="static HTML"):
        qt.assert_non_position_unchanged(
            before_csv,
            before_html,
            after_csv,
            after_html.replace(
                "$35,000.00 |", "$35,000.00 unexpected text |"),
        )

    with pytest.raises(AssertionError, match="CSV metadata/header"):
        qt.assert_non_position_unchanged(
            before_csv,
            before_html,
            after_csv.replace("# Date: 2026-09-21\n", "# Date: 2026-09-21 \n"),
            after_html,
        )

    with pytest.raises(AssertionError, match="position data row"):
        qt.assert_non_position_unchanged(
            before_csv,
            before_html,
            after_csv,
            after_html.replace(
                "</table>",
                '<tr><td colspan="5">unexpected banner</td></tr></table>',
                1,
            ),
        )


def test_duplicate_strategy_symbol_rows_are_rejected():
    """A duplicate must not disappear through dict last-write-wins behavior."""
    duplicate_csv = """strategy,symbol,quantity
Trend Following,ES.v.0,7
Trend Following,ES.v.0,9
"""
    with pytest.raises(AssertionError, match="duplicate CSV position"):
        qt.parse_csv_positions(duplicate_csv)

    duplicate_html = """<h3>Trend Following</h3><table>
<tr><th>Symbol</th><th>Quantity</th><th>Market Price</th><th>Notional</th><th>% of Total</th></tr>
<tr><td>ES.v.0</td><td>7</td><td>$5000.00</td><td>$35,000.00</td><td>100.00%</td></tr>
<tr><td>ES.v.0</td><td>9</td><td>$5000.00</td><td>$45,000.00</td><td>100.00%</td></tr>
</table>"""
    with pytest.raises(AssertionError, match="duplicate HTML position"):
        qt.parse_html_positions(duplicate_html)


def test_manifest_hashes_artifacts_and_does_not_invent_send_telemetry(tmp_path):
    artifact = tmp_path / "synthetic.csv"
    artifact.write_text("strategy,symbol,quantity\nA,ES,7\n", encoding="utf-8")
    manifest_path = tmp_path / "evidence.json"

    qt.write_evidence_manifest(
        manifest_path,
        scope={"portfolio_id": "BOOK_A", "strategy_id": "LIVE_QT_PIPELINE"},
        report_date="2026-09-21",
        checks=[{"name": "synthetic", "passed": True}],
        artifacts=[artifact],
    )

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert manifest["artifacts"][0]["sha256"] == qt.sha256_file(artifact)
    assert manifest["email_send_attempts"]["status"] == "unavailable"
    assert manifest["email_send_attempts"]["count"] is None
    assert manifest["smtp_tested"] is False
    assert manifest["delivery_verified"] is False


def test_fifo_wait_fails_when_probe_exits_before_signal(tmp_path):
    """A broken probe must fail immediately instead of hanging on a FIFO open."""
    fifo = tmp_path / "ready.fifo"
    os.mkfifo(fifo, 0o600)
    fifo_fd = os.open(fifo, os.O_RDWR | os.O_NONBLOCK)
    process = subprocess.Popen(
        [sys.executable, "-S", "-c", "raise SystemExit(17)"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    try:
        with pytest.raises(RuntimeError, match="exited before FIFO signal"):
            qt.wait_for_fifo_signal(process, fifo_fd, "snapshot-loaded", timeout=5)
    finally:
        if process.poll() is None:
            process.kill()
        process.communicate()
        os.close(fifo_fd)


def test_network_guard_requires_only_loopback_and_no_ipv4_routes(tmp_path):
    """An external interface or route must fail the pre-side-effect guard."""
    route = tmp_path / "route"
    route.write_text("Iface\tDestination\tGateway\n", encoding="ascii")
    evidence = qt.require_isolated_network_namespace(
        interface_provider=lambda: [(1, "lo")], ipv4_route_path=route)
    assert evidence["interfaces"] == ["lo"]
    assert evidence["ipv4_route_count"] == 0

    with pytest.raises(qt.UnsafeCertificationInput, match="only interface lo"):
        qt.require_isolated_network_namespace(
            interface_provider=lambda: [(1, "lo"), (2, "eth0")],
            ipv4_route_path=route,
        )

    route.write_text(
        "Iface\tDestination\tGateway\nlo\t00000000\t00000000\n",
        encoding="ascii",
    )
    with pytest.raises(qt.UnsafeCertificationInput, match="no IPv4 routes"):
        qt.require_isolated_network_namespace(
            interface_provider=lambda: [(1, "lo")], ipv4_route_path=route)
