name: Local Linting Enforcement

# on:
#   pull_request:
#     branches:
#       - rebuild

jobs:
  check-linting:
    name: Validate Local Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for Linting Report
        run: |
          if [ ! -f lint_report.txt ]; then
            echo " Linting report not found. Please run linting locally before pushing."
            exit 1
          fi
          
          if grep -q "error" lint_report.txt; then
            echo " Linting errors detected. Fix them before merging."
            exit 1
          fi
          
          echo " Linting successful. PR can be merged."

      - name: Upload Linting Report
        uses: actions/upload-artifact@v4
        with:
          name: linting-report
          path: lint_report.txt
