name: Run Tests and Code Coverage

on:
  push:
    branches:
      - rebuild
  pull_request:
    branches:
      - rebuild

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t trade_ngin .

      - name: Run Unit Tests in Container
        run: |
          docker run --rm trade_ngin ctest --output-on-failure

      - name: Generate Code Coverage Report
        run: |
          docker run --rm trade_ngin gcovr --root . --exclude tests --xml-pretty --output coverage.xml --html --html-details --output coverage.html --filter ../src

      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Upload Cobertura Report
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-report
          path: coverage.xml
