name: Docker Build and Run Pipeline

on:
  push:
    branches:
      - rebuild
  pull_request:
    branches:
      - rebuild

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t trade_ngin .

      - name: Run Docker Container and Execute Build
        run: docker run --rm trade_ngin ./start.up
